# Generated by Django 5.0.6 on 2026-05-10 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('PHQ-9', 'PHQ-9 (Depression)'), ('GAD-7', 'GAD-7 (Anxiety)'), ('PSS', 'PSS (Stress)')], max_length=10)),
                ('score', models.PositiveSmallIntegerField()),
                ('max_score', models.PositiveSmallIntegerField()),
                ('severity', models.CharField(choices=[('minimal', 'Minimal'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=10)),
                ('interpretation', models.TextField()),
                ('answers', models.JSONField(default=list)),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'test_results',
                'ordering': ['-taken_at'],
                'indexes': [models.Index(fields=['user', 'test_type', '-taken_at'], name='test_result_user_id_737cba_idx')],
            },
        ),
    ]
