import { createContext, useContext } from "react";

const FindHelpContext = createContext(null);

export const findHelpData = {
  helplines: [
    {
      id: 1,
      name: "Vandrevala Foundation",
      logo: "https://via.placeholder.com/80x80/fff/E07B54?text=VF",
      description:
        "Cyrus & Priya Vandrevala Foundation is a non-profit organisation that aims to provide significant funding and aid contributions for mental health care and research across India.",
      helpline: "9999666555",
      helplineNote: "(WhatsApp chat support available)",
      time: "24x7 | 7 days a week",
      languages: [
        "English",
        "हिंदी",
        "ગુજરાતી",
        "বাংলা",
        "ಕನ್ನಡ",
        "தமிழ்",
        "తెలుగు",
        "മലയാളം",
        "ଓଡ଼ିଆ",
        "मराठी",
        "தமிழ்",
      ],
      email: null,
      website: "https://www.vandrevalafoundation.com",
    },
    {
      id: 2,
      name: "Tele MANAS",
      logo: "https://via.placeholder.com/80x80/fff/22B1D4?text=TM",
      description:
        "Tele-MANAS is a Government of India initiative, providing a 24/7 free mental health support service. Available in English & 20+ regional languages across India.",
      helpline: "14416",
      helplineNote: null,
      time: "24/7 | 7days a week",
      languages: [
        "অসমীয়া",
        "বাংলা",
        "English",
        "ગુજરાતી",
        "हिंदी",
        "ಕನ್ನಡ",
        "मराठी",
        "নেপালী",
        "ਪੰਜਾਬੀ",
        "سندھی/سرائیکی",
        "தமிழ்",
        "తెలుగు",
        "اردو",
      ],
      email: null,
      website: "https://nimhans.ac.in",
    },
    {
      id: 3,
      name: "MPower Minds",
      logo: "https://via.placeholder.com/80x80/fff/1F2933?text=MP",
      description:
        "The Mpower Minds Helpline is a mental health service dedicated to providing free, confidential support to individuals struggling with emotional and psychological challenges.",
      helpline: "1800-120-820050",
      helplineNote: null,
      time: "24 hours | 7 days a week",
      languages: ["English", "हिंदी", "मराठी"],
      email: "mpowerminds.info@abet.co.in",
      website: "https://www.mpowerminds.com",
    },
    {
      id: 4,
      name: "iCall",
      logo: "https://via.placeholder.com/80x80/fff/52606D?text=iC",
      description:
        "iCall is a psychosocial helpline set up by the Tata Institute of Social Sciences (TISS). It provides professional psychological counselling, information and referral services.",
      helpline: "9152987821",
      helplineNote: null,
      time: "Mon–Sat, 8am–10pm",
      languages: ["English", "हिंदी"],
      email: "icall@tiss.edu",
      website: "https://icallhelpline.org",
    },
    {
      id: 5,
      name: "Snehi",
      logo: "https://via.placeholder.com/80x80/fff/10B981?text=SN",
      description:
        "SNEHI is a non-profit organisation providing emotional support and mental wellness counselling to people in distress. The helpline is run by trained volunteer counsellors.",
      helpline: "044-24640050",
      helplineNote: null,
      time: "Mon–Sat, 8am–10pm",
      languages: ["English", "हिंदी", "தமிழ்"],
      email: "help@snehi.org",
      website: "https://www.snehi.org",
    },
    {
      id: 6,
      name: "AASRA",
      logo: "https://via.placeholder.com/80x80/fff/F59E0B?text=AA",
      description:
        "AASRA is a 24-hour, 365-day NGO providing emotional support for people who are suffering from distress and are in despair. They provide a safe space to express feelings without judgment.",
      helpline: "9820466627",
      helplineNote: null,
      time: "24 hours | 365 days",
      languages: ["English", "हिंदी"],
      email: "aasrahelpline@yahoo.com",
      website: "http://www.aasra.info",
    },
  ],

  therapists: [
    {
      id: 1,
      name: "Dr. Priya Sharma",
      photo: "https://picsum.photos/seed/priya/200/200",
      specialization: "Clinical Psychologist",
      experience: "12 years",
      languages: ["English", "हिंदी", "मराठी"],
      city: "Mumbai",
      mode: ["Online", "In-person"],
      rating: 4.9,
      reviews: 134,
      fee: "₹1,200 / session",
      tags: ["Anxiety", "Depression", "Trauma", "CBT"],
      available: true,
    },
    {
      id: 2,
      name: "Mr. Arjun Mehta",
      photo: "https://picsum.photos/seed/arjun/200/200",
      specialization: "Counselling Psychologist",
      experience: "8 years",
      languages: ["English", "ગુજરાતી", "हिंदी"],
      city: "Ahmedabad",
      mode: ["Online"],
      rating: 4.7,
      reviews: 89,
      fee: "₹900 / session",
      tags: ["Stress", "Relationships", "Career", "Mindfulness"],
      available: true,
    },
    {
      id: 3,
      name: "Dr. Ananya Krishnan",
      photo: "https://picsum.photos/seed/ananya/200/200",
      specialization: "Psychiatrist",
      experience: "15 years",
      languages: ["English", "தமிழ்", "Malayalam"],
      city: "Chennai",
      mode: ["In-person", "Online"],
      rating: 4.8,
      reviews: 201,
      fee: "₹2,000 / session",
      tags: ["OCD", "Bipolar", "Schizophrenia", "Medication"],
      available: false,
    },
    {
      id: 4,
      name: "Ms. Rhea D'Souza",
      photo: "https://picsum.photos/seed/rhea/200/200",
      specialization: "Psychotherapist",
      experience: "6 years",
      languages: ["English", "Konkani", "मराठी"],
      city: "Goa",
      mode: ["Online"],
      rating: 4.6,
      reviews: 57,
      fee: "₹800 / session",
      tags: ["Grief", "Self-esteem", "Anxiety", "LGBTQ+"],
      available: true,
    },
    {
      id: 5,
      name: "Dr. Vikram Nair",
      photo: "https://picsum.photos/seed/vikram/200/200",
      specialization: "Child Psychologist",
      experience: "10 years",
      languages: ["English", "Malayalam", "हिंदी"],
      city: "Kochi",
      mode: ["In-person", "Online"],
      rating: 4.9,
      reviews: 113,
      fee: "₹1,500 / session",
      tags: ["ADHD", "Autism", "Child Therapy", "Family"],
      available: true,
    },
    {
      id: 6,
      name: "Ms. Tanya Bose",
      photo: "https://picsum.photos/seed/tanya/200/200",
      specialization: "Art Therapist",
      experience: "5 years",
      languages: ["English", "বাংলা", "हिंदी"],
      city: "Kolkata",
      mode: ["Online", "In-person"],
      rating: 4.5,
      reviews: 42,
      fee: "₹700 / session",
      tags: ["Trauma", "Creative Therapy", "Depression", "Youth"],
      available: true,
    },
  ],

  selfHelpTechniques: [
    {
      id: 1,
      category: "Anxiety",
      title: "Anxiety: Grounding Technique",
      subtitle: "5-4-3-2-1 Grounding Technique",
      thumbnail: "https://picsum.photos/seed/ground/400/250",
      color: "#22B1D4",
      description:
        "The 5-4-3-2-1 grounding technique is a mindfulness exercise that uses your five senses to help you stay present and calm during moments of anxiety or panic.",
      steps: [
        "👀 Name 5 things you can SEE around you",
        "🤚 Name 4 things you can TOUCH",
        "👂 Name 3 things you can HEAR",
        "👃 Name 2 things you can SMELL",
        "👅 Name 1 thing you can TASTE",
      ],
      duration: "5 mins",
      difficulty: "Beginner",
      videoLabel: "IDENTIFY 5 THINGS YOU CAN SEE",
    },
    {
      id: 2,
      category: "Anxiety",
      title: "Anxiety: Reframing Technique",
      subtitle: "SOAR Technique",
      thumbnail: "https://picsum.photos/seed/soar/400/250",
      color: "#10B981",
      description:
        "The SOAR technique helps you reframe negative thoughts by looking at a situation from multiple perspectives and finding a more balanced, realistic viewpoint.",
      steps: [
        "S — Situation: Describe the situation objectively",
        "O — Old thought: What negative thought comes up?",
        "A — Alternative: What's another way to see it?",
        "R — Realistic: Choose the most balanced thought",
      ],
      duration: "10 mins",
      difficulty: "Intermediate",
      videoLabel: "SOAR TECHNIQUE",
    },
    {
      id: 3,
      category: "Anxiety",
      title: "Anxiety – Breathing Technique",
      subtitle: "4-7-8 Breathing Technique",
      thumbnail: "https://picsum.photos/seed/breath/400/250",
      color: "#8B5CF6",
      description:
        "The 4-7-8 breathing technique is a simple yet powerful breathing exercise that activates your parasympathetic nervous system to reduce anxiety and promote relaxation.",
      steps: [
        "Inhale quietly through your nose for 4 seconds",
        "Hold your breath for 7 seconds",
        "Exhale completely through your mouth for 8 seconds",
        "Repeat the cycle 3–4 times",
      ],
      duration: "5 mins",
      difficulty: "Beginner",
      videoLabel: "4-7-8 BREATHING TECHNIQUE",
    },
    {
      id: 4,
      category: "Depression",
      title: "Depression: Behavioral Activation",
      subtitle: "Schedule Pleasurable Activities",
      thumbnail: "https://picsum.photos/seed/behav/400/250",
      color: "#F59E0B",
      description:
        "Behavioral activation is a core CBT strategy for depression. It involves scheduling enjoyable or meaningful activities to break the cycle of avoidance and low mood.",
      steps: [
        "List 10 activities you used to enjoy",
        "Rate each by pleasure (1–10) and ease (1–10)",
        "Pick 2 activities for today",
        "Schedule them at specific times",
        "Reflect on how you feel after each",
      ],
      duration: "15 mins",
      difficulty: "Intermediate",
      videoLabel: "BEHAVIORAL ACTIVATION",
    },
    {
      id: 5,
      category: "Stress",
      title: "Stress: Progressive Muscle Relaxation",
      subtitle: "PMR Technique",
      thumbnail: "https://picsum.photos/seed/pmr/400/250",
      color: "#EF4444",
      description:
        "Progressive Muscle Relaxation (PMR) involves tensing and then releasing each muscle group in your body. It helps reduce physical tension associated with stress.",
      steps: [
        "Find a quiet, comfortable place to sit or lie down",
        "Start with your feet — tense them for 5 seconds",
        "Release and notice the sensation for 10 seconds",
        "Move up to calves, thighs, abdomen, arms, face",
        "Finish with a few deep breaths",
      ],
      duration: "20 mins",
      difficulty: "Beginner",
      videoLabel: "PMR TECHNIQUE",
    },
    {
      id: 6,
      category: "Mindfulness",
      title: "Mindfulness: Body Scan Meditation",
      subtitle: "Full Body Awareness",
      thumbnail: "https://picsum.photos/seed/bodyscan/400/250",
      color: "#22B1D4",
      description:
        "A body scan meditation guides your attention through each part of your body, promoting awareness, relaxation, and a deep sense of calm.",
      steps: [
        "Lie down comfortably and close your eyes",
        "Take 3 deep breaths",
        "Focus on the top of your head — notice any sensations",
        "Slowly move attention down — face, neck, chest, arms…",
        "End at your feet; breathe and rest for 2 mins",
      ],
      duration: "15 mins",
      difficulty: "Beginner",
      videoLabel: "BODY SCAN MEDITATION",
    },
  ],

  categories: ["All", "Anxiety", "Depression", "Stress", "Mindfulness"],
};

export function FindHelpProvider({ children }) {
  return (
    <FindHelpContext.Provider value={findHelpData}>
      {children}
    </FindHelpContext.Provider>
  );
}

export const useFindHelp = () => useContext(FindHelpContext);
