# Generated by Django 5.0.6 on 2026-05-10 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_label', models.CharField(choices=[('good', '😊 Good'), ('okay', '😐 Okay'), ('low', '😔 Low'), ('anxious', '😣 Anxious'), ('stressed', '😡 Stressed')], max_length=10)),
                ('mood_score', models.PositiveSmallIntegerField()),
                ('note', models.TextField(blank=True)),
                ('logged_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mood_entries',
                'ordering': ['-logged_date'],
                'indexes': [models.Index(fields=['user', '-logged_date'], name='mood_entrie_user_id_ff3cca_idx')],
                'unique_together': {('user', 'logged_date')},
            },
        ),
    ]
